
project_id = "jhxhhccqgbpfxwhbosdm"

[functions.create-user]
verify_jwt = false

[functions.create-worksite]
verify_jwt = false

[functions.get-worksites]
verify_jwt = false

[functions.update-worksite]
verify_jwt = false

[functions.update-user]
verify_jwt = false
